name: Build PR
run-name: "PR Build: #${{ github.event.pull_request.number }} (${{ github.run_attempt }}.${{ github.run_number }}) - ${{ github.event.pull_request.title }}"

on:
  pull_request:
    branches:
      - $default-branch

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # REMOVE this job if this repo is not a Python package
  gen-requirements:
    uses: "howsoai/.github/.github/workflows/compile-requirements.yml@main"
    secrets: inherit
    with:
      #######################################################################################
      # TODO: Replace package names below with relevant Howso dependencies for this project #
      #######################################################################################
      upstream-packages: 'amalgam-lang-py howso-engine-py howso-synthesizer-py howso-validator-py howso-validator-enterprise-py'

  build:
    needs: ['gen-requirements']
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      build-type: "PR"

  xray:
    needs: ['build']
    uses: "howsoai/.github/.github/workflows/scan-pull-request.yml@main"
    secrets: inherit

  # This job is here to have only one final step to add for "Status Checks"
  # in GitHub, instead of adding every leaf test from 'build-test-package'
  final-check:
    needs: ['build', 'gen-requirements', 'xray']
    if: always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
    runs-on: ubuntu-latest
    steps:
      - run: exit 1