name: Reusable WF - Compile Requirements

on:
  workflow_call:
    inputs:
      upstream-packages:
        description: A whitespace separated list of Howso package dependencies [DEPRECATED].
        type: string
        required: false
      extras:
        description: A whitespace-separated list of Python "extras" that should be installed into requirements-<version>-dev.txt
        type: string
        required: false
        default: "dev"
      branch:
        description: A branch to commit requirements to (defaults to github.head_ref)
        type: string
        required: false
        default: ${{ github.head_ref }}
      force-rebuild:
        description: Force a requirements rebuild even if no changes are detected
        type: boolean
        required: false
        default: false

jobs:
  check-requirements:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      dev_req_file: ${{ steps.detect-changes.outputs.dev-req-file }}
      changes: ${{ steps.detect-changes.outputs.changes }}
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Check for requirements changes
        id: detect-changes
        run: |
          # Determine which type of requirements/setup file exists in this repo
          if [ -e "pyproject.toml" ]; then
            echo "Found pyproject.toml"
            req_file="pyproject.toml"
          elif [ -e "requirements.in" ]; then
            echo "Found requirements.in"
            req_file="requirements.in"
            if [ -e "requirements-dev.in" ]; then
              dev_req_file="requirements-dev.in"
            fi
          fi

          # Warn if setup.py is used (should migrate to pyproject.toml)
          if [ -e "setup.py" ]; then
            echo "::warning file=setup.py::Please update to a pyproject.toml"
          fi

          # Check for changes in the requirements files on the current branch compared to default branch
          git fetch
          git status
          changes=$(git diff "origin/${{ github.event.repository.default_branch }}" --name-only -- "$req_file")

          if [[ ! -n "$changes" && ! -e "requirements-3.11.txt" ]]; then
            echo "Requirements.txt does not exist!"
            changes="no requirements.txt"
          fi

          if [ -n "$changes" ]; then
            echo "Changes found in $req_file on branch ${{ inputs.branch }}."
          else
              echo "No changes to $req_file detected on ${{ inputs.branch }}."
          fi

          echo "dev-req-file: $dev_req_file"

          echo "changes=$(echo $changes)" >> $GITHUB_OUTPUT
          echo "dev-req-file=$(echo $dev_req_file)" >> $GITHUB_OUTPUT

  compile-requirements:
    needs: ['check-requirements']
    if: needs.check-requirements.outputs.changes != '' || inputs.force-rebuild == true
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      changes-pushed: ${{ steps.commit-changes.outputs.changes-pushed }}
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
      max-parallel: 1  # Necessary to avoid merge conflicts
      matrix:
        type: ['3.8', '3.9', '3.10', '3.11', 'licenses']
    steps:

      - uses: actions/checkout@v4
        with:
          # Check out with a PAT so that the workflow can make commits that re-trigger the PR build
          token: ${{ secrets.HOWSOAI_WORKFLOW_AUTOMATION_TOKEN }}
          ref: ${{ inputs.branch }}
      
      - name: Set up Python
        if: matrix.type != 'licenses'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.type }}

      - name: Set up Python (3.11 only)
        if: matrix.type == 'licenses'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Compile requirements
        if: matrix.type != 'licenses'
        id: compile-requirements
        run: |
          # Only check labels on PR events
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            labels=$(gh pr view --json labels "${{ inputs.branch }}")
            # Skip if this version has already been checked
            while IFS= read -r label; do
              if [[ "$label" == "generated requirements [${{ matrix.type }}]" ]]; then
                echo "Requirements for Python ${{ matrix.type }} have already been reevaluated. Skipping."
                exit 0
              fi
            done < <(echo "$labels" | jq -r '.labels[] | .name')
          fi
          # Pull latest changes
          git pull
          # Set extra index URL
          if [[ -n "${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}" ]]; then
            export PIP_EXTRA_INDEX_URL=https://vsts-build@diveplane.com:${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}@dpbuild.jfrog.io/artifactory/api/pypi/pypi-edge/simple
          fi
          # Install pip-tools and run pip-compile
          pip install -U pip pip-tools
          if [[ "${{ needs.check-requirements.outputs.dev_req_file }}" == "requirements-dev.in" ]]; then
            # --allow-unsafe: needed so that setuptools can be compiled, which is a dependency of pytest
            pip-compile requirements.in --resolver=backtracking --upgrade requirements.in --generate-hashes --no-emit-index-url --allow-unsafe -o requirements-${{ matrix.type }}.txt
            pip-compile requirements-dev.in --resolver=backtracking --upgrade requirements.in --generate-hashes --no-emit-index-url --allow-unsafe -o requirements-${{ matrix.type }}-dev.txt
          else
            # --allow-unsafe: needed so that setuptools can be compiled, which is a dependency of pytest
            pip-compile --resolver=backtracking --upgrade --generate-hashes --no-emit-index-url --allow-unsafe -o requirements-${{ matrix.type }}.txt
            # Check to see if any requirements were actually generated; don't commit "empty" requirements files
            if [[ $(wc -l <requirements-${{ matrix.type }}.txt) -le 7 ]]; then
              cat requirements-${{ matrix.type }}.txt
              echo "Removing empty requirements-${{ matrix.type }}.txt as it is empty."
              rm -f requirements-${{ matrix.type }}.txt
            fi
            # Generate dev/other extras requirements
            extras=""
            for extra in ${{ inputs.extras }}; do
              extras+="--extra $extra "
            done
            echo "Got extras: $extras"
            # Only generate dev requirements if there are extras
            if [[ -n "$extras" ]]; then
              pip-compile $extras --resolver=backtracking --upgrade --generate-hashes --no-emit-index-url --allow-unsafe -o requirements-${{ matrix.type }}-dev.txt
            fi
          fi
          # Add a label to indicate that this version has already been checked
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            gh pr edit --add-label "generated requirements [${{ matrix.type }}]" "${{ inputs.branch }}"
          fi

      - name: Generate third-party licenses
        if: matrix.type == 'licenses'
        id: gen-licenses
        run: |
          # Only check labels on PR events
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # Skip if this version has already been checked or if there are no 'main' requirements
            labels=$(gh pr view --json labels "${{ inputs.branch }}")
            while IFS= read -r label; do
              if [[ "$label" == "generated licenses" || ! -e "requirements-3.11.txt" ]]; then
                echo "Licenses for Python ${{ matrix.type }} have already been evaluated, or there are no required 3rd party packages to generate licenses from."
                exit 0
              fi
            done < <(echo "$labels" | jq -r '.labels[] | .name')
          fi
          # Pull latest changes
          git pull
          rm -f ./LICENSE-3RD-PARTY.txt
          # Set extra index URL
          if [[ -n "${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}" ]]; then
            export PIP_EXTRA_INDEX_URL=https://vsts-build@diveplane.com:${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}@dpbuild.jfrog.io/artifactory/api/pypi/pypi-edge/simple
          fi
          pip install -r requirements-3.11.txt
          # Do not include Howso software in the 3rd party license file
          pip uninstall amalgam-lang howso-engine howso-synthesizer howso-validator howso-validator-enterprise howso-visuals howso-openapi-client -y
          pip install pip-licenses
          pip-licenses --with-authors --with-urls --with-license-file --with-description --format=plain-vertical  > ./LICENSE-3RD-PARTY.txt
          # Add a label to indicate that licenses have already been generated
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            gh pr edit --add-label "generated licenses" "${{ inputs.branch }}"
          fi

      - name: Commit changes
        id: commit-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes to pip requirements or third-party licenses detected. Making a new commit..."
            git config user.name "howso-automation"
            git config user.email "support@howso.com"
            git add .
            git commit -m "Automated requirements/license generation [${{ matrix.type }}]"
            git push
            echo "changes-pushed=$(echo 'true')" >> $GITHUB_OUTPUT
          else
            echo "No changes detected in the repository."
          fi
  
  update-labels:
    needs: ['check-requirements', 'compile-requirements']
    if: (needs.check-requirements.outputs.changes != '' || inputs.force-rebuild == true) && github.event_name =='pull_request'
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_TOKEN: ${{ github.token }}
    steps:

      - uses: actions/checkout@v4
        with:
          # Check out with a PAT so that the workflow can make commits that re-trigger the PR build
          token: ${{ secrets.HOWSOAI_WORKFLOW_AUTOMATION_TOKEN }}
          ref: ${{ inputs.branch }}

      - name: Remove labels
        run: |
          automated_labels=("generated requirements [3.8]" "generated requirements [3.9]" "generated requirements [3.10]" "generated requirements [3.11]" "generated licenses")
          labels=$(gh pr view --json labels "${{ inputs.branch }}")

          echo "$labels" | jq -r '.labels[] | .name' | while read -r label; do
            for auto_label in "${automated_labels[@]}"; do
              if [[ "$label" == "$auto_label" ]]; then
                  echo "Found label: $label"
                  gh pr edit --remove-label "$label" "${{ inputs.branch }}"
              fi
            done
          done