name: Reusable WF - Create Pull Request

on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        required: false
        default: false
      branch:
        description: The name of the new branch to create
        type: string
        required: true
      title:
        description: The PR title
        type: string
        required: true
      body:
        description: The PR body
        type: string
        required: false
        default: "Automted PR"
      repo:
        description: The repository to create a PR on
        type: string
        required: false
      recipe-reviewers:
        description: Add the usual suspects as reviewers for recipe rerun PRs
        type: boolean
        required: false
        default: false

jobs:

  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
        GH_TOKEN: ${{ github.token }}
    steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.HOWSOAI_WORKFLOW_AUTOMATION_TOKEN }}
        ref: ${{ inputs.branch }}
        repository: ${{ inputs.repo }}

    - name: Create PR
      run: |
        if [[ ${{ inputs.dry-run }} == true ]]; then
          echo "Dry run with --base=${{ github.event.repository.default_branch }}, --title=${{ inputs.title }}, --body==${{ inputs.body }}"
          exit 0
        fi

        # Make sure there isn't already a PR open for this branch
        echo "Checking for existing PR from branch '${{ inputs.branch }}'..."
        existing_pr=$(gh pr list --head "${{ inputs.branch }}" --json number --jq '.[0].number')
        if [[ -n "$existing_pr" ]]; then
          echo "A PR already exists for branch '${{ inputs.branch }}' (PR #$existing_pr). Skipping."
          exit 0
        fi

        REVIEWERS=""
        if [[ ${{ inputs.recipe-reviewers }} == true ]]; then
          REVIEWERS="--reviewer jdbeel --reviewer cademack --reviewer jackx111"
        fi

        if [[ -n "${{ inputs.repo }}" ]]; then
          export GH_TOKEN=${{ secrets.HOWSOAI_WORKFLOW_AUTOMATION_TOKEN }}
          gh pr create --repo "${{ inputs.repo }}" --base "main" --title "${{ inputs.title }}" --body "${{ inputs.body }}" $REVIEWERS
        else
          gh pr create --base ${{ github.event.repository.default_branch }} --title "${{ inputs.title }}" --body "${{ inputs.body }}" $REVIEWERS
        fi

        # To trigger Actions, we must make a commit under the PAT
        sleep 5
        git config user.name "howso-automation"
        git config user.email "support@howso.com"
        git commit --allow-empty -m "Trigger workflows (empty commit)"
        git push