name: Reusable WF - Create Pull Request

on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        required: false
        default: false
      branch:
        description: The name of the new branch to create
        type: string
        required: true
      title:
        description: The PR title
        type: string
        required: true
      body:
        description: The PR body
        type: string
        required: false
        default: "Automted PR"

jobs:

  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
        GH_TOKEN: ${{ github.token }}
    steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.HOWSOAI_WORKFLOW_AUTOMATION_TOKEN }}
        ref: ${{ inputs.branch }}

    - name: Create PR
      run: |
        if [[ ${{ inputs.dry-run }} == true ]]; then
          echo "Dry run with --base=${{ github.event.repository.default_branch }}, --title=${{ inputs.title }}, --body==${{ inputs.body }}"
          exit 0
        fi
        gh pr create --base ${{ github.event.repository.default_branch }} --title "${{ inputs.title }}" --body "${{ inputs.body }}"
        # To trigger Actions, we must make a commit under the PAT
        sleep 5
        git config user.name "howso-automation"
        git config user.email "support@howso.com"
        git commit --allow-empty -m "Trigger workflows (empty commit)"
        git push