name: Reusable WF - Create Pull Request

on:
  workflow_call:
    inputs:
      branch:
        description: The name of the new branch to create
        type: string
        required: true
      title:
        description: The PR title
        type: string
        required: true
      body:
        description: The PR body
        type: string
        required: false
        default: "Automted PR"

jobs:

  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
        GH_TOKEN: ${{ github.token }}
    steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.HOWSOAI_WORKFLOW_AUTOMATION_TOKEN }}
        ref: ${{ inputs.branch }}

    - name: Create PR
      run: |
        gh pr create --base ${{ github.event.repository.default_branch }} --title "${{ inputs.title }}" --body "${{ inputs.body }}"