name: Reusable WF - Create New Branch

on:
  workflow_call:
    inputs:
      branch:
        description: The name of the new branch to create
        type: string
        required: true

jobs:

  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      branch: ${{ steps.create-branch.outputs.branch }}

    steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.HOWSOAI_WORKFLOW_AUTOMATION_TOKEN }}
        ref: ${{ github.head_ref }}
    
    - name: Create new branch
      id: create-branch
      run: |
        git config user.name "howso-automation"
        git config user.email "support@howso.com"
        echo "Creating branch ${{ inputs.branch }}"
        git checkout -b ${{ inputs.branch }}
        git push --set-upstream origin ${{ inputs.branch }}