name: Reusable WF - Get Dependency Details

on:
  workflow_call:
    inputs:
      owner:
        required: false
        type: string
        default: "howsoai"
      repo:
        required: true
        type: string
      payload:
        required: false
        type: string
      skip-version-json-check:
        required: false
        type: boolean
        default: false
    outputs:
      run-type:
        description: "Run type to be used in GitHub CLI command for dependency query"
        value: ${{ jobs.get-dependency-details.outputs.run-type }}
      run-id:
        description: "Run id to be used in GitHub CLI command for dependency query"
        value: ${{ jobs.get-dependency-details.outputs.run-id }}
      build-date:
        description: "The datetime of the run (non-release)"
        value: ${{ jobs.get-dependency-details.outputs.build-date }}
      build-title:
        description: "The display title of the run (non-release)"
        value: ${{ jobs.get-dependency-details.outputs.build-title }}
      head-sha:
        description: "The commit hash used for the workflow run"
        value: ${{ jobs.get-dependency-details.outputs.head-sha }}
      url:
        description: "A URL pointing to the workflow run"
        value: ${{ jobs.get-dependency-details.outputs.url }}

jobs:

  get-dependency-details:
    runs-on: ubuntu-latest
    outputs:
      run-type: ${{ steps.dependency.outputs.run-type }}
      run-id: ${{ steps.dependency.outputs.run-id }}
      build-date: ${{ steps.dependency.outputs.build-date }}
      build-title: ${{ steps.dependency.outputs.build-title }}
      head-sha: ${{ steps.dependency.outputs.head-sha }}
      url: ${{ steps.dependency.outputs.url }}
    steps:
      - uses: actions/checkout@v4

      - name: Get dependency details
        id: dependency
        env:
          GH_TOKEN: ${{ secrets.HOWSOAI_WORKFLOW_AUTOMATION_CLASSIC_TOKEN }}
        run: |
          echo "Parsing JSON payload: '${{ inputs.payload }}'..."
          ID=""

          if ! [[ -n "${{ inputs.payload }}" && $(echo '${{ inputs.payload }}' | jq 'has("${{ inputs.repo }}")') == true ]]; then
              # Repo not specified in payload; check version.json
              if [ "${{ inputs.skip-version-json-check }}" = true ]; then
                echo "No JSON payload given with repo ${{ inputs.repo }}, and skip-version-json-check flag is set. Exiting."
                exit 0
              elif ! [[ -e version.json ]]; then
                # For the set-metadata workflow to be sufficiently generalized,
                # the skip-version-json-check flag cannot be set for amalgam or howso-engine,
                # even if the current repository does not have a version.json. Thus, kindly
                # exit if a version.json does not exist.
                echo "Current repository does not have a version.json"
                exit 0
              fi
              echo "No JSON payload given with repo ${{ inputs.repo }}, using version.json"
              ID=$(jq -r '.dependencies."${{ inputs.repo }}"' version.json)
              echo "Found build ID for ${{  inputs.repo }} in version.json: '$ID'"
          else
              ID=$(echo '${{ inputs.payload }}' | jq -r '."${{ inputs.repo }}"')
              echo "Payload contains build ID for ${{ inputs.repo }}: '$ID'"
          fi

          echo "Searching for ${{ inputs.repo }} build id '$ID'..."
          if gh release view --repo ${{ inputs.owner }}/${{ inputs.repo }} "$ID" > /dev/null 2>&1; then
              # Release
              echo "Found release build"
              echo "run-type=$(echo "release")" >> $GITHUB_OUTPUT
              # Set metadata (sha, url)
              details=$(gh release view --repo ${{ inputs.owner }}/${{ inputs.repo }} $ID --json targetCommitish,url)
              head_sha=$(echo "$details" | jq '.targetCommitish')
              url=$(echo "$details" | jq '.url')
              echo "head-sha=$(echo $head_sha | tr -d '"')" >> $GITHUB_OUTPUT
              echo "url=$(echo $url | tr -d '"')" >> $GITHUB_OUTPUT
          elif gh run view --repo ${{ inputs.owner }}/${{ inputs.repo }} "$ID" > /dev/null 2>&1; then
              # Prerelease (workflow run)
              echo "Found non-release build"
              echo "run-type=$(echo "run")" >> $GITHUB_OUTPUT
              # Set metadata (build date, title, sha, url)
              details=$(gh run view --repo ${{ inputs.owner }}/${{ inputs.repo }} $ID --json createdAt,displayTitle,headSha,url)
              build_date=$(echo "$details" | jq '.createdAt')
              build_title=$(echo "$details" | jq '.displayTitle')
              head_sha=$(echo "$details" | jq '.headSha')
              url=$(echo "$details" | jq '.url')
              echo "build-date=$(echo $build_date | tr -d '"')" >> $GITHUB_OUTPUT
              echo "build-title=$(echo $build_title | tr -d '"')" >> $GITHUB_OUTPUT
              echo "head-sha=$(echo $head_sha | tr -d '"')" >> $GITHUB_OUTPUT
              echo "url=$(echo $url | tr -d '"')" >> $GITHUB_OUTPUT
          else
              echo "Build not found"
              exit 1
          fi

          echo "run-id=$(echo "$ID")" >> $GITHUB_OUTPUT